
image: ubuntu:18.04 
stages:
 - test
 
test:  
 stage: test  
 script:    
 - apt-get update -qy    
 - apt-get install -y python3-pip python3
 - apt-get install -y python3-requests
 - cd src    
 - python3 -m unittest  test
